### ISSUE TITLE
Plans for a plugin?

### ISSUE THREAD

**Issue by pconesa** [rsanchezgarc/cesped#3]
HI Ruben! Any plan to integrate this in Scipion as a plugin, shouldn't be too hard?

**Comment by rsanchezgarc** [comment]
Hi Pablo!
This repo is mostly a benchmark for machine learning people, thus their usage in new projects is not direct. I am working on a user-friendly version. Once it is ready, I will be happy to integrate it in Scipion

**Comment by pconesa** [comment]
niiice!! LEt me know if you need any assistance with it! Un abrazo!
